accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('login/', views.LoginView.as_view(), name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(),
         name="password_change"),
    path("password-change/done/", auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('register/', views.register, name='register'),
    path('about-us/', views.about_us, name='about-us'),
]

tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.TaskListView.as_view(), name='list'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('complete/<int:uid>', views.complete_task, name='complete'),
    path('delete/<int:uid>', views.delete_task, name='delete'),
    path('details/<int:pk>', views.TaskDetailsView.as_view(), name='details'),
    path('edit/<int:pk>', views.TaskEditView.as_view(), name='edit'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import tasks.views

urlpatterns = [
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', tasks.views.index)
]

accounts/models.py
from django.db import models

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.utils import timezone


class TodoItem(models.Model):
    description = models.CharField(max_length=64)
    is_completed = models.BooleanField('Выполнено', default=False)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='tasks')

    def __str__(self):
        return self.description.lower()

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return redirect('tasks/details', args=[self.pk])

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "first_name")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd["password2"]:
            raise forms.ValidationError("Пароли не совпадают!")
        return cd["password2"]

tasks/forms.py
from django import forms

from tasks.models import TodoItem


class AddTaskForm(forms.Form):
    description = forms.CharField(max_length=64, label='')


class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ('description',)
        labels = {'description': ''}
        

accounts/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from accounts.forms import LoginForm
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required


class LoginView(View):
    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password']
            )
            if user is None:
                return HttpResponse('Неправильный логин и/или пароль')

            if not user.is_active:
                return HttpResponse('Ваш аккаунт заблокирован')

            login(request, user)
        return render(request, 'accounts/login.html', {"form": form})

    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return render(request, 'accounts/login.html', {"form": form})


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data["password"])
            new_user.save()

            return render(request, "accounts/registration_complete.html",
                              {"new_user": new_user})
    else:
        form = RegistrationForm()

    return render(request, "accounts/register.html", {"user_form": form})


@login_required
def about_us(request):
    user_form = request.user
    return render(request, "accounts/about_us.html", {"user_form": user_form})

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import TodoItem
from .forms import TodoItemForm
from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from datetime import datetime


def index(request):
    return redirect('/accounts/login')


def complete_task(request, uid):
    t = TodoItem.objects.get(id=uid)
    t.is_completed = True
    t.save()
    return HttpResponse('OK')


def delete_task(request, uid):
    t = TodoItem.objects.get(id=uid)
    t.delete()
    messages.success(request, "Deleted")
    return redirect('/tasks/list')


class TaskListView(LoginRequiredMixin, ListView):
    model = TodoItem
    context_object_name = 'tasks'
    template_name = 'tasks/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        u = self.request.user
        if u.is_anonymous:
            return []
        return qs.filter(owner=u)


class TaskCreateView(View):
    def post(self, request, *args, **kwargs):
        form = TodoItemForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            messages.success(request, 'Successfully added')
            return redirect('/tasks/list')

        return render(request, 'tasks/create.html', {"form": form})

    def get(self, request, *args, **kwargs):
        form = TodoItemForm()
        return render(request, 'tasks/create.html', {"form": form})


class TaskDetailsView(DetailView):
    model = TodoItem
    template_name = 'tasks/details.html'


class TaskEditView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(request.POST, instance=t)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.updated = datetime.now()
            new_task.save()
            return redirect('/tasks/list')

        return render(request, 'tasks/edit.html', {"form": form, "tasks": t})

    def get(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = TodoItemForm(instance=t)
        return render(request, 'tasks/edit.html', {"form": form, "tasks": t})

accounts/templates/accounts/about_us.html
{% extends 'base.html' %}

{% block title %}О сайте{% endblock %}
{% block extra_head %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

{%endblock %}

{% block main_content %}
<div style="margin-left: 15%; width: 70%;">
        <h2>Здравствуйте {{ user_form.username }}</h2>
        <p>Каждый день вы сталкиваетесь с десятками задач, но запоминть все, не удастся.
            Здесь поможем мы.
            Данный сайт помогает вам делать заметки( ставить задачи, таски) онлайн и следить за тем, что выполнено а что нет.</p>
        <p>Вы можете удалить задачу нажав на <i class="material-icons">delete</i></p>
        <p>Нажав на какую либо задачу, вы перейдете в "свойства" задачи. Там же вы можете редактировать свою задачу
        по соответствующей ссылке.</p>
        <p>В меню (в верхнем левом углу) вы найдете несколько ссылок, а именно: </p>
        <ul>
            <li>(Задачи) Для просмотра всех существующих заметок(задач)</li>
            <li>(Добавить задачу) Для добавления какой либо задачи</li>
            <li>(Сменить пароль) Также вы можете поменять пароль вашего нынешнего аккаунта</li>
            <li>(Выйти) А также, вы можете выйти с учетной записи и, например, войти с другого аккаунта :)</li>
        </ul>


        <p>На всякий случай оставлю ссылки для регистрации и входа в акканут:</p>
        <li><a href="{% url 'register' %}">Зарегистрироваться</a></li>
        <li><a href="{% url 'login' %}">Залогиниться</a></li>
    <hr>
        <p>
            По всем вопросам и рекомендациям обращаться в Телеграмм <a href="https://t.me/samadov_09">t.me/samadov_09</a>
        </p>

</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Войдите{% endblock %}

{% block main_content %}
<div class="w3-card-4">
  <div class="w3-container w3-brown">
    <h2>Вход</h2>
     {% if form.errors %}
    <p>Ошибка: пароль или логин неправильные. Попробуйте снова!</p>
  {% else %}
    <p style="margin-left: 25%; width: 50%;">Введите логин/пароль:</p>
  {% endif %}
  </div>
  <form class="w3-container" action="." method="post" style="margin-left: 25%; width: 50%;">
    <p>
    <label class="w3-text-brown"><b>Login</b></label>
    <input class="w3-input w3-border w3-sand" name="username" type="text"></p>
    <p>
    <label class="w3-text-brown"><b>Password</b></label>
    <input type="password" class="w3-input w3-border w3-sand" name="password"></p>
    <p>
      {% csrf_token %}
    <button class="w3-btn w3-brown">Entry</button></p>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}

{% block main_content %}
<div class="w3-card-4">
  <div class="w3-container w3-brown">
    <h2>Создать аккаунт</h2>
    <p>Воспользуйтесь следующей формой:</p>
    <form action="." method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Создать"></p>
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/registration_complete.html
{% extends "base.html" %}

{% block title %}Ура! Успех{% endblock %}
{% block main_content %}
<div class="w3-card-4">
  <div class="w3-container w3-brown">
    <h1>Все готово, {{ new_user.first_name }}!</h1>
    <p>Ваш аккаунт был создан, теперь можно
    <a href="{% url 'login' %}">залогиниться</a></p>
  </div>
</div>
{% endblock %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Создать задачу{% endblock %}


{% block main_content %}
    <form action="." method="post" class="w3-container tasks-create " style="margin-left: 25%; width: 50%;">
        <h2 class="w3-text-blue"><b>Создать задачу</b></h2>
        {{ form }}
        {% csrf_token %}
        <button class="w3-btn w3-blue" type="submit">+</button>
    </form>
{% endblock %}

tasks/templates/tasks/details.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задача {{ object.id }} {% endblock %}
{% block extra_head %}
<link rel="stylesheet"
href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
crossorigin="anonymous">
{% endblock %}

{% block main_content %}
<form class="w3-container" action="." method="post" style="margin-left: 25%; width: 50%;">
    <h1>Задача</h1>
    <p><b>Описание</b>: {{ object }}</p>
    <ul>
        <li>
            {{ object.is_completed|yesno:"Выполнена,Не выполнена" }}
        </li>
        <li><i class="far fa-calendar-alt"></i> Создана: {{ object.created|date:"Y-M-d H:i" }}</li>
        <li><i class="far fa-clock"></i> Последнее изменение: {{ object.updated|date:"Y-M-d H:i" }}</li>
        <li><i class="far fa-edit"></i> <a href="{% url 'tasks:edit' pk=object.pk %}"
                                                >Редактировать</a></li>
    </ul>
    <i class="fas fa-clipboard-list"></i> <a href="{% url 'tasks:list' %}">Назад к списку</a>
</form>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends 'base.html' %}

{% block title %}Изменить задачу{% endblock %}

{% block main_content %}
<form action="#" method="post" class="w3-container tasks-create " style="margin-left: 25%; width: 50%;">
    <h1 class="w3-text-blue">Поменять задачу</h1>
    {% csrf_token %}
    {{ form }}
    <p><button class="w3-btn w3-blue" type="submit">Сохранить</button></p>
</form>
{% endblock %}

tasks/templates/tasks/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Задачи на день{% endblock %}

{% block extra_head %}
    <script src="{% static 'js/script.js' %}"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}

{% block main_content %}
            <form class="w3-container " style="margin-left: 25%; width: 50%;" method="get">
                <h2>Текущие задачи</h2>
                {% for task in tasks %}
                    <p>
                    {% if task.is_completed %}
                        <input class="w3-check" type="checkbox" checked="checked"
                               disabled="disabled" data-uid={{ task.id }} />
                        <a href="{% url 'tasks:details' task.id %}" class="completed"> {{ task }}</a>
                    {% else %}
                        <input class="w3-check checkbox2"  data-uid={{ task.id }} type="checkbox" />
                        <a href="{% url 'tasks:details' task.id %}" > {{ task }}</a>
                    {% endif %}
                    <a href="{% url 'tasks:delete' task.id %}" style="float: right"><i class="material-icons" style="color: black;">delete</i></a>
                    </p>
                <hr>
                {% endfor %}
            </form>
{% endblock  %}

templates/base.html
{% load static %}
<html>
    <head>
        <title>{% block title %}MMM{% endblock %}</title>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
                crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">


        {% block extra_head %}
        {% endblock %}
    </head>
    <body>
    <div>
        <div class="row">

            <div class="side_bar col" style="margin: left-top">
                {% block side_bar %}
                    {% if user.is_authenticated %}
                <div class="w3-sidebar w3-bar-block" style="display:none" id="mySidebar">
                      <button onclick="w3_close()" class="w3-bar-item w3-button w3-large">Close &times;</button>
                      <a href="{% url 'tasks:list' %}" class="w3-bar-item w3-button">Задачи</a>
                      <a href="{% url 'tasks:create' %}" class="w3-bar-item w3-button">Добавить задачу</a>
                      <a href="{% url 'password_change' %}" class="w3-bar-item w3-button">Сменить пароль</a>
                      <a href="{% url 'about-us' %}" class="w3-bar-item w3-button">О сайте</a>
                      <a href="{% url 'logout' %}" class="w3-bar-item w3-button">Выйти</a>
                </div>
                <div class="w3-teal">
                    <button class="w3-button w3-teal w3-xlarge" onclick="w3_open()">☰</button>
                    <div class="w3-container">
                        <h1>My Page</h1>
                    </div>
                </div>
                {% endif %}
                {% endblock %}
            </div>
            <div class="w3-green w3-display-container" style="width: 50%; margin-left:25%;">
                {% for message in messages %}
                <span onclick="this.parentElement.style.display='none'"
                class="w3-button w3-small w3-display-topright">&times;</span>
                <h3>{{ message }}</h3>
                {% endfor %}
            </div>
                {% block main_content %}
                {% endblock %}


        </div>
    </div>
    <script>
function w3_open() {
  document.getElementById("mySidebar").style.width = "25%";
  document.getElementById("mySidebar").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}
</script>
    </body>
</html>